#define R_REACTOR 2
#define G_REACTOR 130
#define B_REACTOR 195

#define R_REACTOR_CENTER 190
#define G_REACTOR_CENTER 255
#define B_REACTOR_CENTER 255

#define WAIT_REACTOR 90
#define WAIT_RAINBOW 90
#define WAIT_SPARKS 90
#define WAIT_LOADING 90

#define NUMPIXELS 7 